// index.ts — the evidence domain (plan 07 D6 claim extract, E10 deterministic parts; research 05 §6;
// plan 02 §6.4; plan 10 B8): the `rules_v1` claim extractor, the hand-set source reliability model,
// the structured-field comparator, and the stored-row → `NewsItem` wrapper. Pure; no I/O.
export {
  availabilityClass,
  CLAIM_DIRECTIONS,
  CLAIM_TEXT_CAP,
  CLAIM_TYPES,
  claimFold,
  DESIGNATIONS,
  extractClaim,
  extractItemClaim,
  RULE_IDS,
  ruleHits,
  RULES_V1,
  RULES_V1_TABLE,
  toClaimExtract,
  type AvailabilityClass,
  type ClaimDirection,
  type ClaimType,
  type Designation,
  type RuleId,
  type RulesV1Claim,
} from "./claims.js";
export {
  calibrationState,
  HAND_SET_NOTE,
  INJECTION_RELIABILITY_CAP,
  newsReliabilitySource,
  posteriorAllowed,
  RELIABILITY_PRIORS,
  RELIABILITY_SOURCES,
  reliabilityOf,
  reliabilityPrior,
  reliabilitySourceOf,
  SEASON_OUTLOOK_ZERO_WEEK,
  seasonOutlookWeight,
  type CalibrationState,
  type Reliability,
  type ReliabilityContext,
  type ReliabilitySource,
  type ScoredClaimType,
} from "./reliability.js";
export {
  statusClass,
  structuredDisagreement,
  type StructuredDisagreement,
  type StructuredFacts,
} from "./structured.js";
export {
  isNewsFeed,
  NEWS_FEED_KEYS,
  newsClaim,
  newsItemFromRow,
  readStoredNewsRow,
  type NewsClaimFields,
  type NewsFeed,
  type StoredNewsRow,
} from "./news.js";
