// build.ts — the engine's frozen expected outputs for the recorded golden (plan 08 §6 step 1:
// "Expected outputs are frozen under fixtures/golden/ with a manifest hash (plan 05 §3.1 step 4) so
// an engine change that silently alters a score fails even if the ESPN fixture is unchanged").
// `buildGolden` is pure over the recorded fixtures; tests/golden/freeze.ts writes its output.
import path from "node:path";
import { contentSha256, type Json } from "../../scripts/espn-fixture/canonical.js";
import {
  normalizeSettings,
  score,
  statLineFromEspn,
  verify,
} from "../../src/domain/scoring/index.js";
import {
  finalWeeks,
  LEAGUES,
  MANIFEST,
  type LeagueSlot,
  recordedScoringSettings,
  recordedTeamWeeks,
  ROOT,
  type StatEntry,
} from "./recorded.js";

export const GOLDEN_DIR = path.join(ROOT, "fixtures/golden");
export const GOLDEN_PATH = path.join(GOLDEN_DIR, "espn-recorded.json");
export const GOLDEN_MANIFEST_PATH = path.join(GOLDEN_DIR, "manifest.json");

/** [player id, engine points on the actual line, engine points on ESPN's projected line]. */
export type GoldenRow = [number, number | null, number | null];

export interface GoldenFile {
  readonly $comment: string;
  readonly version: 1;
  readonly leagues: Record<
    LeagueSlot,
    { settings_hash: string; weeks: Record<string, GoldenRow[]> }
  >;
}

function enginePoints(
  entry: StatEntry | undefined,
  position: number,
  settings: ReturnType<typeof normalizeSettings>,
): number | null {
  if (entry === undefined) return null;
  return score(statLineFromEspn({ raw: entry.stats }, position).line, settings).points;
}

/** The engine's points for every rostered player-week of the recorded final weeks. */
export function buildGolden(): GoldenFile {
  const leagues = {} as GoldenFile["leagues"];
  for (const league of LEAGUES) {
    const settings = normalizeSettings(recordedScoringSettings(league));
    const weeks: Record<string, GoldenRow[]> = {};
    for (const week of finalWeeks(league)) {
      const rows: GoldenRow[] = [];
      for (const team of recordedTeamWeeks(league, week)) {
        for (const p of team.players) {
          rows.push([
            p.player_id,
            enginePoints(p.actual, p.position, settings),
            enginePoints(p.projected, p.position, settings),
          ]);
        }
      }
      weeks[String(week)] = rows.sort((a, b) => a[0] - b[0]);
    }
    leagues[league] = { settings_hash: settings.settings_hash, weeks };
  }
  return {
    $comment:
      "Frozen engine outputs over fixtures/espn/recorded (plan 08 §6 step 1): per league slot the settings_hash and, per final week, [ESPN player id, engine points on the actual line, engine points on ESPN's projected line]. Generated by tests/golden/freeze.ts; never edited by hand. Engine evidence is the comparison with ESPN's appliedStats in tests/golden/espn-recorded.test.ts — this file only pins the engine's own output.",
    version: 1,
    leagues,
  };
}

/** The recorded files the golden reads, with their manifest hashes (a re-recording forces a refreeze). */
export function goldenSources(): { path: string; sha256: string }[] {
  const wanted = new Set<string>();
  for (const league of LEAGUES) {
    wanted.add(`recorded/${league}/mSettings.json`);
    for (const w of finalWeeks(league))
      wanted.add(`recorded/${league}/mBoxscore.sp${String(w)}.json`);
  }
  return MANIFEST.files
    .filter((f) => wanted.has(f.path))
    .map((f) => ({ path: f.path, sha256: f.sha256 }))
    .sort((a, b) => (a.path < b.path ? -1 : 1));
}

/** The golden manifest: the frozen file's content hash and the recorded sources it was built from. */
export function goldenManifest(golden: GoldenFile): Json {
  return {
    $comment:
      "Manifest of fixtures/golden (plan 05 §3.1 step 4): sha256 = canonical-JSON content hash (scripts/espn-fixture/canonical.ts contentSha256). Regenerate with tests/golden/freeze.ts after a deliberate engine change or a re-recording.",
    files: [{ path: "espn-recorded.json", sha256: contentSha256(golden as unknown as Json) }],
    sources: goldenSources(),
  };
}

/**
 * Every recorded player-week (actual and projected) whose engine score does NOT match ESPN — the
 * freeze refuses to run unless this is empty (the frozen file never pins a known mismatch).
 */
export function goldenMismatches(): string[] {
  const out: string[] = [];
  for (const league of LEAGUES) {
    const settings = normalizeSettings(recordedScoringSettings(league));
    for (const week of finalWeeks(league)) {
      for (const team of recordedTeamWeeks(league, week)) {
        for (const p of team.players) {
          for (const entry of [p.actual, p.projected]) {
            if (entry === undefined) continue;
            const line = statLineFromEspn({ raw: entry.stats }, p.position).line;
            const v = verify(line, settings, {
              total: entry.appliedTotal,
              by_stat: entry.appliedStats,
            });
            if (!v.match) out.push(`${league} w${String(week)} ${String(p.player_id)}`);
          }
        }
      }
    }
  }
  return out;
}
