#!/usr/bin/env -S npx tsx
// gen-manifest.ts — generates the per-view, per-entity drift manifest (fixtures/drift/entity-manifest
// .json) from the COMMITTED recorded fixtures, after anonymisation: plan 05 §3.1 step 4 (observed key
// sets, enum values, array-length ranges per view and entity; never hand-edited), plan 01 §7 (the
// in-call detector's manifest), research 03 §F.3 step 4. Offline; it refuses unless every fixture
// still hashes to the recording manifest (provenance) and the repo scanner passes the output.
//
// Usage:  scripts/dev/with-node.sh npx tsx scripts/gen-manifest.ts [--check]
//                                     [--fixtures <dir, default fixtures/>] [--out <file>]
//   --check writes nothing: exit 1 when the committed manifest is not what the fixtures generate.
// Exit: 0 written / current · 1 stale, refused or error · 2 usage.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { isEspnView } from "../src/providers/espn/types.js";
import {
  canonicalize,
  contentSha256,
  isObject,
  parseJsonStrict,
  type Json,
  type JsonObject,
} from "./espn-fixture/canonical.js";
import {
  ENTITY_MANIFEST_PATH,
  ENTITY_MANIFEST_VERSION,
  buildViewManifest,
  validateEntityManifest,
  type EntityManifest,
  type EntityViewManifest,
} from "./espn-fixture/entity-manifest.js";
import { formatJson } from "./espn-fixture/format-json.js";
import { REPO_ROOT } from "./espn-fixture/http.js";
import { scanWithRepoScanner } from "./espn-fixture/scan.js";

export class ManifestRefusal extends Error {
  constructor(
    message: string,
    /** Where (paths, view names) — never a value. */
    readonly where: readonly string[] = [],
  ) {
    super(message);
  }
}

type Scan = (text: string, label: string) => { clean: boolean; findings: string[]; error?: string };

export interface GenOptions {
  /** The `fixtures/` directory: the recording manifest is `<dir>/espn/manifest.json`. */
  fixturesDir: string;
  /** Injected for tests; defaults to the repo scanner (with the local deny-list). */
  scan?: Scan;
}

/** One recorded response: its parts (in order), re-assembled when it was split. */
interface Response {
  views: string[];
  status: number;
  parts: { rel: string; sha256: string }[];
  body: Json;
}

const COMMENT =
  "The per-view, per-entity drift manifest (plan 01 §7; plan 05 §3.1 step 4) the in-call detector reads. Generated by scripts/gen-manifest.ts from the committed recorded fixtures (fixtures/espn/manifest.json, whose canonical sha256 is recording_manifest_sha256) — never hand-edited; regenerate after re-recording (`--check` tells whether it is current). Each view is observed over WHOLE responses (split parts re-assembled) recorded as that view alone, else inside a composite request. Patterns: `$` the root, `.key` a property, `[]` every array element, `{}` every value of a map-like object (every key an integer, or any key outside [A-Za-z_$][\\w$]*). Per view: `observed` key sets, `enums` (UPPER_SNAKE strings outside free-text keys; statSourceId, statSplitTypeId, lineupSlotId, defaultPositionId, proTeamId), `array_lengths`, `nodes` and `optional` (keys some node lacks; every other observed key was on every node — a candidate for a required set, never more), `map_keys` (integer keys of map-like objects: stat ids, slot ids, weeks), and `entities` (team, member, rosterEntry, playerPoolEntry, player, stats, scheduleItem, matchupSide, settings.*, status, … — the same observations grouped per entity, keys relative to the entity node). `errors`: the recorded error bodies (synthetic bodies are never evidence and never here). Paths, keys and enum tokens only: no value, name or id of any league.";

/** Reads and checks the recording manifest and every fixture it lists (provenance). */
export function loadRecorded(fixturesDir: string): {
  manifest: JsonObject;
  host: string;
  season: number;
  capturedAt: string;
  responses: Response[];
} {
  const file = path.join(fixturesDir, "espn", "manifest.json");
  const manifest = parseJsonStrict(readFileSync(file, "utf8"));
  if (
    !isObject(manifest) ||
    manifest.version !== 1 ||
    typeof manifest.host !== "string" ||
    !Number.isInteger(manifest.season) ||
    typeof manifest.captured_at !== "string" ||
    !Array.isArray(manifest.files)
  )
    throw new ManifestRefusal("the recording manifest is malformed");
  const { host, season, captured_at: capturedAt } = manifest;
  const problems: string[] = [];
  const groups = new Map<
    string,
    { entry: JsonObject; rel: string; sha256: string; body: Json }[]
  >();
  for (const e of manifest.files) {
    if (!isObject(e) || typeof e.path !== "string" || typeof e.sha256 !== "string") {
      problems.push("a recording manifest entry is malformed");
      continue;
    }
    const rel = e.path;
    if (!/^recorded\/[\w.-]+\/[\w.-]+\.json$/.test(rel) || rel.includes("..")) {
      problems.push(`${rel}: not a recorded fixture path`);
      continue;
    }
    if (e.derived !== false) {
      problems.push(`${rel}: not recorded evidence (derived)`);
      continue;
    }
    const abs = path.join(fixturesDir, "espn", rel);
    if (!existsSync(abs)) {
      problems.push(`${rel}: listed but missing`);
      continue;
    }
    const body = parseJsonStrict(readFileSync(abs, "utf8"));
    if (contentSha256(body) !== e.sha256) {
      problems.push(`${rel}: its content no longer hashes to the recording manifest`);
      continue;
    }
    const key = rel.replace(/\.p\d+\.json$/, ".json");
    groups.set(key, [...(groups.get(key) ?? []), { entry: e, rel, sha256: e.sha256, body }]);
  }
  const responses: Response[] = [];
  for (const [key, members] of [...groups.entries()].sort(([a], [b]) => (a < b ? -1 : 1))) {
    const first = members[0]?.entry;
    const views = Array.isArray(first?.views)
      ? first.views.filter((v): v is string => typeof v === "string")
      : [];
    const status = typeof first?.status === "number" ? first.status : 0;
    const partOf = (e: JsonObject) => (isObject(e.part) ? e.part : null);
    const ordered = [...members].sort(
      (a, b) => Number(partOf(a.entry)?.index ?? 0) - Number(partOf(b.entry)?.index ?? 0),
    );
    let body: Json;
    if (ordered.length === 1 && partOf(ordered[0]?.entry ?? {}) === null)
      body = ordered[0]?.body ?? null;
    else {
      const parts = ordered.map((m) => partOf(m.entry));
      const array = parts[0]?.array;
      const contiguous =
        typeof array === "string" &&
        parts.every(
          (p, i) => p !== null && p.index === i + 1 && p.of === ordered.length && p.array === array,
        );
      if (!contiguous) {
        problems.push(`${key}: its parts are not contiguous 1..n along one array`);
        continue;
      }
      if (array === "$") body = ordered.flatMap((m) => (Array.isArray(m.body) ? m.body : []));
      else {
        const bodies = ordered.map((m) => (isObject(m.body) ? m.body : {}));
        const items = bodies.flatMap((b) => (Array.isArray(b[array]) ? b[array] : []));
        body = { ...bodies[0], [array]: items };
      }
    }
    responses.push({
      views,
      status,
      parts: ordered.map((m) => ({ rel: `espn/${m.rel}`, sha256: m.sha256 })),
      body,
    });
  }
  if (problems.length)
    throw new ManifestRefusal(
      `refusing to generate: ${String(problems.length)} provenance problem(s)`,
      problems,
    );
  return { manifest, host, season: season as number, capturedAt, responses };
}

/**
 * Which responses serve which view: every 200 response recorded as that view ALONE; a composite
 * response serves only a view with no solo recording (the probe manifest's rule — scripts/probe.ts
 * viewSources). Skeletons (an unknown view) and error bodies serve no view.
 */
export function responsesByView(responses: readonly Response[]): Map<string, Response[]> {
  const solo = new Map<string, Response[]>();
  const composite = new Map<string, Response[]>();
  for (const r of responses) {
    if (r.status !== 200 || !r.views.length || !r.views.every(isEspnView)) continue;
    const into = r.views.length === 1 ? solo : composite;
    for (const v of r.views) into.set(v, [...(into.get(v) ?? []), r]);
  }
  const out = new Map<string, Response[]>();
  for (const v of [...new Set([...solo.keys(), ...composite.keys()])].sort())
    out.set(v, solo.get(v) ?? composite.get(v) ?? []);
  return out;
}

const viewOf = (rs: readonly Response[]): EntityViewManifest =>
  buildViewManifest(
    rs.map((r) => r.body),
    rs.flatMap((r) => r.parts.map((p) => ({ path: p.rel, sha256: p.sha256 }))),
  );

/** Generates the manifest and its exact file text (validated and scanned; nothing written). */
export async function generate(o: GenOptions): Promise<{ manifest: EntityManifest; text: string }> {
  const { manifest: recording, host, season, capturedAt, responses } = loadRecorded(o.fixturesDir);
  const views: Record<string, EntityViewManifest> = {};
  for (const [v, rs] of responsesByView(responses)) views[v] = viewOf(rs);
  const errors = responses.filter((r) => r.status >= 400);
  if (!errors.length) throw new ManifestRefusal("no recorded error body to observe");
  const manifest: EntityManifest = {
    $comment: COMMENT,
    version: ENTITY_MANIFEST_VERSION,
    generator: "scripts/gen-manifest.ts",
    host,
    season,
    captured_at: capturedAt,
    recording_manifest_sha256: contentSha256(recording),
    views,
    errors: viewOf(errors),
  };
  validateEntityManifest(manifest);
  const text = await formatJson(canonicalize(manifest as unknown as Json, { sortArrays: false }));
  const scan = o.scan ?? ((t: string, l: string) => scanWithRepoScanner(t, l));
  const r = scan(text, ENTITY_MANIFEST_PATH);
  if (!r.clean)
    throw new ManifestRefusal(
      `refusing to write: the repo scanner refused the manifest${r.error ? ` (${r.error})` : ""}`,
      r.findings.slice(0, 20),
    );
  return { manifest, text };
}

/** The view names whose sections differ between two manifest texts (for a `--check` report). */
export function staleViews(current: string, generated: string): string[] {
  const parse = (t: string): JsonObject => {
    try {
      const v = parseJsonStrict(t);
      return isObject(v) ? v : {};
    } catch {
      return {};
    }
  };
  const a = parse(current);
  const b = parse(generated);
  const av = isObject(a.views) ? a.views : {};
  const bv = isObject(b.views) ? b.views : {};
  const names = [...new Set([...Object.keys(av), ...Object.keys(bv)])].sort();
  const out = names.filter((n) => JSON.stringify(av[n] ?? null) !== JSON.stringify(bv[n] ?? null));
  if (JSON.stringify(a.errors ?? null) !== JSON.stringify(b.errors ?? null)) out.push("(errors)");
  for (const k of ["recording_manifest_sha256", "host", "season", "captured_at", "version"])
    if (JSON.stringify(a[k]) !== JSON.stringify(b[k])) out.push(`(${k})`);
  return out;
}

export interface CliResult {
  exit: number;
  message: string;
}

export async function runCli(argv: readonly string[], scan?: Scan): Promise<CliResult> {
  let check = false;
  let fixturesDir = path.join(REPO_ROOT, "fixtures");
  let out: string | null = null;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const val = (): string | null => {
      const v = argv[++i];
      return v === undefined || v.startsWith("--") ? null : v;
    };
    if (a === "--check") check = true;
    else if (a === "--fixtures" || a === "--out") {
      const v = val();
      if (v === null) return { exit: 2, message: `${a} needs a value` };
      if (a === "--fixtures") fixturesDir = path.resolve(v);
      else out = path.resolve(v);
    } else return { exit: 2, message: `unknown argument #${String(i + 1)}` };
  }
  const target = out ?? path.join(fixturesDir, "drift", "entity-manifest.json");
  try {
    const { text } = await generate({ fixturesDir, ...(scan ? { scan } : {}) });
    if (check) {
      const current = existsSync(target) ? readFileSync(target, "utf8") : "";
      if (current === text) return { exit: 0, message: "the entity manifest is current" };
      const stale = staleViews(current, text);
      return {
        exit: 1,
        message: `the entity manifest is stale (${stale.join(", ") || "layout"}) — run scripts/gen-manifest.ts`,
      };
    }
    writeFileSync(target, text);
    return { exit: 0, message: `wrote ${path.relative(REPO_ROOT, target)}` };
  } catch (e) {
    const where = e instanceof ManifestRefusal ? e.where.map((w) => `\n  ${w}`).join("") : "";
    return { exit: 1, message: `${e instanceof Error ? e.message : String(e)}${where}` };
  }
}

async function main(): Promise<void> {
  const r = await runCli(process.argv.slice(2));
  process.stderr.write(`gen-manifest: ${r.message}\n`);
  process.exitCode = r.exit;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href)
  void main();
