// make-waiver-excerpt.ts — writes fixtures/nflverse/backtest/ (plan 10 A9a's 2024–2025 excerpt;
// research 05 §1.6, §8.4 #4) from nflverse release files downloaded by hand. Not a test and never
// run by CI; the download is a grounding step (no agent or test fetches). Afterwards: add the two
// files to fixtures/nflverse/ATTRIBUTION.md, run prettier on the JSON, regenerate the report with
// `UPDATE_EVALS=1 scripts/dev/with-node.sh npx vitest run --project unit tests/backtest`, and review
// the diff (the scanner runs at commit).
//
//   scripts/dev/with-node.sh npx tsx tests/backtest/helpers/make-waiver-excerpt.ts <download-dir>
//
// <download-dir> holds `stats_player_stats_player_week_2024.parquet` and
// `stats_player_stats_player_week_2025.parquet` (the `<tag>_<file>` names make-fixtures.ts uses),
// from https://github.com/nflverse/nflverse-data/releases/download/stats_player/<file>.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  BACKTEST_DIR,
  buildWaiverExcerpt,
  type BacktestFile,
  type BacktestManifest,
} from "./waiver-excerpt.js";

/** The seasons research 05 §1.6 replayed. */
const SEASONS = [2024, 2025] as const;

const src = process.argv[2];
if (src === undefined) throw new Error("usage: make-waiver-excerpt.ts <download-dir>");
const dir: string = src;

mkdirSync(BACKTEST_DIR, { recursive: true });
const files: BacktestFile[] = [];
for (const season of SEASONS) {
  const bytes = readFileSync(join(dir, `stats_player_stats_player_week_${String(season)}.parquet`));
  const built = await buildWaiverExcerpt(new Uint8Array(bytes), season);
  for (const p of built.parts) writeFileSync(join(BACKTEST_DIR, p.name), p.text);
  writeFileSync(join(BACKTEST_DIR, built.entry.path), `${JSON.stringify(built.header, null, 2)}\n`);
  files.push(built.entry);
}
const manifest: BacktestManifest = {
  $comment:
    "nflverse backtest excerpts (CC-BY 4.0, see ../ATTRIBUTION.md) for plan 10 A9a's hindsight replay (research 05 §1.6, §8.4 #4). Generated by tests/backtest/helpers/make-waiver-excerpt.ts; read by tests/backtest/helpers/waiver-excerpt.ts, which re-hashes every part. `upstream.sha256` pins the exact release file.",
  retrieved: new Date().toISOString().slice(0, 10),
  files,
};
writeFileSync(join(BACKTEST_DIR, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
console.error(
  files
    .flatMap((f) => f.parts.map((p) => `${p.path} ${String(p.bytes)} B ${String(p.rows)} rows`))
    .join("\n"),
);
