// make-replacement-excerpt.ts — writes tests/backtest/data/stats_player_week/ (plan 10 B7: "recompute
// the 2025 and 2024 baselines from the nflverse files"; research 05 §3.1, §4.1) from nflverse release
// files downloaded by hand. The rows and columns are exactly B1's waiver-replay excerpt
// (`buildWaiverExcerpt`, BACKTEST_RULE: REG weeks 1–17, QB/RB/WR/TE, the columns the reference
// scoring reads) — the same filter research 05 §3.1 states — so one excerpt serves both. Not a test
// and never run by CI; the download is a grounding step (no agent or test fetches). Afterwards run
// prettier on the JSON files and review the diff (the scanner runs at commit).
//
//   scripts/dev/with-node.sh npx tsx tests/backtest/helpers/make-replacement-excerpt.ts <download-dir>
//
// <download-dir> holds `stats_player_week_2024.parquet` and `stats_player_week_2025.parquet` from
// https://github.com/nflverse/nflverse-data/releases/download/stats_player/<file>.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { REPLACEMENT_DATA_DIR } from "./replacement-data.js";
import { buildWaiverExcerpt, type BacktestFile, type BacktestManifest } from "./waiver-excerpt.js";

const SEASONS = [2024, 2025] as const;

const src = process.argv[2];
if (src === undefined) throw new Error("usage: make-replacement-excerpt.ts <download-dir>");
const dir: string = src;

mkdirSync(REPLACEMENT_DATA_DIR, { recursive: true });
const files: BacktestFile[] = [];
for (const season of SEASONS) {
  const bytes = readFileSync(join(dir, `stats_player_week_${String(season)}.parquet`));
  const built = await buildWaiverExcerpt(new Uint8Array(bytes), season);
  for (const p of built.parts) writeFileSync(join(REPLACEMENT_DATA_DIR, p.name), p.text);
  // this directory's README carries the attribution; the generator is this file
  const header = {
    ...built.header,
    $comment: built.header.$comment
      .replace("see ../ATTRIBUTION.md", "see README.md")
      .replace("make-waiver-excerpt.ts", "make-replacement-excerpt.ts"),
  };
  writeFileSync(
    join(REPLACEMENT_DATA_DIR, built.entry.path),
    `${JSON.stringify(header, null, 2)}\n`,
  );
  files.push(built.entry);
}
const manifest: BacktestManifest = {
  $comment:
    "nflverse stats_player_week excerpts (CC-BY 4.0, see README.md) for plan 10 B7's replacement-level regression (research 05 §3.1, §4.1). Generated by tests/backtest/helpers/make-replacement-excerpt.ts; read by tests/backtest/helpers/replacement-data.ts through loadBacktestSeason, which re-hashes every part. `upstream.sha256` pins the exact release file.",
  retrieved: new Date().toISOString().slice(0, 10),
  files,
};
writeFileSync(
  join(REPLACEMENT_DATA_DIR, "manifest.json"),
  `${JSON.stringify(manifest, null, 2)}\n`,
);
console.error(
  files
    .flatMap((f) => f.parts.map((p) => `${p.path} ${String(p.bytes)} B ${String(p.rows)} rows`))
    .join("\n"),
);
